
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
      firebase_app_distribution(
          app: "1:63422403363:android:daca08bce9fba416fc3296",
          firebase_cli_token:"1//03QEWdISxUGCRCgYIARAAGAMSNwF-L9Ir_-tTwgBzqaVZtXd9L99KLvHM1TXaQgmDfTeTZfgytjdVIz2UJ2Hr9Sf2Bqmz5YfVtYY",
          android_artifact_type:"APK",
          android_artifact_path:"../app/outputs/flutter-apk/app-production-release.apk",
          testers: "s.sanabani@gmail.com",
          release_notes:"First Fastlane Firebase Distribution YouTube Video!"
        )
  end
end
